api_token: 6809006471:AAHjJFLQuYNc8vn8axFVWs9dtTOf8XwK0M4
admin_id: 6138338289
mongodb_url: mongodb://localhost:27017
max_images_pattern: 10
#TODO: Add max_users_pattern

celery_broker: redis://127.0.0.1:6379/4