api_token: 6809006471:AAHjJFLQuYNc8vn8axFVWs9dtTOf8XwK0M4
admin_id: 6138338289
mongodb_url: mongodb://mongo:27017
max_images_pattern: 10
#TODO: Add max_users_pattern

celery_broker: redis://redis-db:6379/5

redis_host: redis-db
redis_port: 6379
redis_db: 0

minio_endpoint: minio:9000
minio_access_key: your_access_key
minio_secret_key: your_secret_key
minio_secure: False
