version: '3.8'

services:
  redis-db:
    image: redis:latest
    environment:
      REDIS_DATABASES: 0
      REDIS_PORT: 6379
    volumes:
      - redis_data:/root/redis
    ports:
      - "6379:6379"

volumes:
  redis_data:
