version: '3.8'

services:
  redis-db:
    image: redis:latest
    environment:
      REDIS_DATABASES: 0
      REDIS_PORT: 6379
    volumes:
      - redis_data:/root/redis
    ports:
      - "6379:6379"

  rabbit:
    image: rabbitmq:latest
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: your_access_key
      MINIO_SECRET_KEY: your_secret_key
    volumes:
      - ./data:/data
    command: server /data

volumes:
  redis_data:
  rabbit_data:
